Updated HUDl to standard process loop
RIT-EVT/HUDL pull request #11
Opened 2024-01-23 00:52 UTC by ActuallyTaylor

2024-01-23 14:16 UTC, mjmagee991 requested changes
A couple details to clean up

2024-01-23 14:16 UTC, mjmagee991 commented on include/HUDL/HUDL.hpp
> +     * The corner of the display that will content will be displayed in.
```suggestion
     * The corner of the display that the content will be displayed in.
```

2024-01-23 14:16 UTC, mjmagee991 commented on include/HUDL/HUDL.hpp
> +     * +The internal LCD used for for the HUDL to display.
```suggestion
     * The internal LCD used for for the HUDL to display.
```

2024-01-23 14:16 UTC, mjmagee991 commented on include/HUDL/HUDL.hpp
> +     * A static function that retrieves the column number for a specified corner. This is used
```suggestion
     * Retrieves the column number for a specified corner. This is used
```
You generally don't want to mention things about whatever you're documenting that are present in the thing itself. It just increases your chances of updating the thing and forgetting to update the comment. This includes stuff like static and any data types.

Make sure to fix this in other comments as well

2024-01-23 14:16 UTC, mjmagee991 commented on include/HUDL/HUDL.hpp
> +     * The size of the CAN object dictionary.
```suggestion
     * The size of the CANopen object dictionary.
```

2024-01-23 14:16 UTC, mjmagee991 commented on include/HUDL/HUDL.hpp
> +     * The CAN object dictionary.
```suggestion
     * The CANopen object dictionary.
```

2024-01-23 14:16 UTC, mjmagee991 commented on src/HUDL/HUDL.cpp
> +void HUDL::process() {
```suggestion

void HUDL::process() {
```

2024-01-23 14:16 UTC, mjmagee991 commented on src/HUDL/HUDL.cpp
> +}
```suggestion
}

```

2024-01-27 18:43 UTC, aclowmclaughlin requested changes
Looks good except for some minor changes!

2024-01-27 18:43 UTC, aclowmclaughlin commented on include/HUDL/HUDL.hpp
> +    /** NANO ID for the Motor Controller */
```suggestion
    /** NODE ID for the Motor Controller */
```

2024-01-27 18:43 UTC, aclowmclaughlin commented on include/HUDL/HUDL.hpp
> +    /** A boolean that tracks whether or not the headers have been set. */
```suggestion
    /**  Tracks whether or not the headers have been set. */
```

2024-01-27 21:46 UTC, mjmagee991 approved these changes
Nice work

2024-01-30 00:03 UTC, aclowmclaughlin approved these changes
"This shit 🔥 "

2024-01-30 00:03 UTC, merged